version: '3.8'

services:
  lms-manager:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: lms-manager
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - ./backups:/app/backups
      - /var/www/moodle:/moodle:ro
      - /var/www/moodledata:/moodledata:ro
    environment:
      - TZ=Asia/Jakarta
      - DEBUG=false
    networks:
      - lms-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  nginx:
    image: nginx:alpine
    container_name: lms-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - lms-manager
    networks:
      - lms-network

networks:
  lms-network:
    driver: bridge

volumes:
  data:
  logs:
  backups:
